### ISSUE TITLE
repeat doesn't work in <table> in IE11

### ISSUE THREAD

**Issue by warpech** [Juicy/imported-template#10]
Repeating template rows in <table> doesn't work in IE11.

I tried to apply instructions from https://www.polymer-project.org/docs/polymer/databinding-compat.html but it still doesn't work.

This page also doesn't work in IE11 (may be related): http://juicy.github.io/imported-template/examples/wellBehaved_partial.html

**Comment by miyconst** [comment]
I guess this issue is outdated together with Polymer 0.5.

Anyway, Polymer 1.x officially does not support `dom-repeat` in tables under IE: 
https://github.com/Polymer/polymer/issues/1567

**Comment by miyconst** [comment]
Closing this issue as outdated.
