### ISSUE TITLE
Add support for IMD

### ISSUE THREAD

**Issue by tomalec** [Juicy/imported-template#11]
Polymer released [IMD](https://github.com/PolymerLabs/IMD) (AMD approach to HTML Imports)

Maybe we could use it if available, and if specified 
https://github.com/PolymerLabs/IMD#html-dependencies,

Or event create separated custom element, that imports content using `define`.

**Comment by warpech** [comment]
Reading from the README, it does it have a likelyhood to become a standard, and even Polymer considers it experimental.

Could you explain what problems does it solve for us?

**Comment by tomalec** [comment]
Closing as no longer relevant. We would rather adapt to HTML Modules one the spec will settle.
