### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by warpech** [Juicy/imported-template#14]
Including for the case fixed by https://github.com/Juicy/imported-template/commit/74a96309ba2d93712706cc5cca8eccf8da06cc46

**Comment by tomalec** [comment]
I have added few just for this issue https://github.com/Juicy/imported-template/commit/bda9d765189194ad59e587d444d005f1a4305e6a

**Comment by tomalec** [comment]
I have setup travis for us
https://travis-ci.org/Juicy/imported-template

**Comment by tomalec** [comment]
So far it fails in Safari heavily, but I do not have a Mac to investigate that :/ https://github.com/Juicy/juicy-html/issues/13

**Comment by miyconst** [comment]
Right now we have 14 failing and 5 passing test. Should be fixed. It's one of our core components.

**Comment by miyconst** [comment]
My bad, I was testing with an old version of `juicy-html`.

**Comment by tomalec** [comment]
2 maj 2016 18:10 "Konstantin" <notifications@github.com> napisał(a):
>
> My bad, I was testing with an old version of juicy-html.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
<https://github.com/Juicy/imported-template/issues/14#issuecomment-216279207>

**Comment by tomalec** [comment]
That is why we have Travis https://travis-ci.org/Juicy/imported-template
Right now it fails in Safari 7, which we probably can remove from supported browsers list

**Comment by warpech** [comment]
Let's only care about Safari 9 at this point.

**Comment by warpech** [comment]
@tomalec Can this be closed?
