### ISSUE TITLE
It can't handle more than one script tag when using partials

### ISSUE THREAD

**Issue by malx122** [Juicy/imported-template#15]
I have two htmls that having a structure like this:
```
<template>
    <template is="dom-bind">
        ...
    </template>
    <script>
         ...
    </script>
</template>
```
Those belong to two partials joined together with <starcounter-include>.
This will result in an error at line 45 at imported-template.html:
```
Uncaught NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
```
Either of them by themself works good and it also works if I remove the script tag in any of them. (But I of course need the script tag in both)

**Comment by warpech** [comment]
Fix released in 1.0.3. Thanks @malx122 and @miyconst!
