### ISSUE TITLE
Safari 9 support

### ISSUE THREAD

**Issue by tomalec** [Juicy/imported-template#19]
@miyconst  Could you take a look, some test were failing on SauceLabs: https://travis-ci.org/Juicy/imported-template/builds/100953397

**Comment by miyconst** [comment]
All tests pass in Safari 8.0.8, trying to update to the 9 version.

**Comment by tomalec** [comment]
Released with [1.1.0](https://github.com/Juicy/imported-template/releases/tag/1.1.0)
