### ISSUE TITLE
Invalid script execution order

### ISSUE THREAD

**Issue by miyconst** [Juicy/imported-template#21]
In shimmed browsers such as IE and FF scripts in the partials are executed after Polymer applies bindings.

This example demonstrates what I mean: http://juicy.github.io/imported-template/examples/polymer_partial.html

In Chrome this [code](https://github.com/Juicy/imported-template/blob/gh-pages/examples/partials/polymer_binding.html#L13) is executed before Polymer applies bindings.

In IE and FF the code executes after Polymer applies bindings which results in the following warning:

```
[dom-bind::_annotatedComputationEffect]: compute method `getPartialName` not defined 
```

The same pattern works with even handlers because Polymer checks for the event handler only when it is needed, not immediately.

cc @tomalec, @warpech

**Comment by miyconst** [comment]
Ping.

**Comment by tomalec** [comment]
It's not an easy one, considering the way the webcomponentsjs shim works, and the fact that Polymer does not expose any stamp method for `dom-bind` or any other way to control lifecycle.

I have pushed a workaround, but it has a serious downside - shimmed (ones from imported template) scripts are executed before they are attached to a DOM.

You can see it via this `console.log`: https://github.com/Juicy/imported-template/blob/bbf35c29f2ef4cb5c13cdc8370d1be32cd0bf209/examples/partials/polymer_binding.html#L11

**Comment by alshakero** [comment]
This is long solved right?

**Comment by alshakero** [comment]
I tested Chrome, Edge and FF and they're all running in the same order.

**Comment by alshakero** [comment]
Works as expected in Safari 
![image](https://user-images.githubusercontent.com/17054134/36487131-775060de-1720-11e8-9bd2-f87bca6a05aa.png)

**Comment by tomalec** [comment]
Great, so let's close it as no longer a problem, we could reopen it back again if we manage to reproduce it.
