### ISSUE TITLE
V1 migration risks - element will rendered before element upgrade

### ISSUE THREAD

**Issue by tomalec** [Juicy/imported-template#25]
There is a risk I found in migrating to V1 which may require some actions/discussions:

`is` attribute is at some risk in spec, or at least there is lack of consensus as Apple does not want to implement it:
https://github.com/w3c/webcomponents/issues/509

It's still in spec, and hopefully will be supported by polyfill. Anyway, if it will be removed element in current shape will be not so useful.

Given

``` html
<section>
    ...Some code
   <imported-template content="pathto/template/to/include.html"><p>Some code that should not get rendered</p></imported-template>
</section>
```

`<p>` element will be rendered (until `imported-template` element definition is provided). So, lazy loading the definition will no longer ba an option. We could, workaround it as Polymer does https://github.com/Polymer/polymer/blob/2.0-preview/README.md#v1-custom-elements : 

``` html
<section>
    ...Some code
   <imported-template content="pathto/template/to/include.html"><template><p>Some code that should not get rendered</p></template></imported-template>
</section>
<link rel="import" href="/pathto/imported-template.html"/>
```

Which will be rendered slightly better, but:
1. I would say there are too many "template" words in code,
2. `imported-template` element will be rendered and could take part in box model,
3. It would be hard to filter it (by `juicy-composition`) together with other `<template>` elements

Also, personally, I found `<template is>` syntax more self-explanatory and suggestive.

//cc @warpech, @miyconst

**Comment by warpech** [comment]
I totally agree with your observation, but - AFAIK, `is=""` is part of the V1 spec right now. There is a danger of it being removed, but before that happens, we should not worry. If it happens, we will live on the polyfill until we choose one of the solutions that you proposed above.

Do I understand correct?

**Comment by tomalec** [comment]
> Do I understand correct?

Yes.

I would say we should monitor it, as I think forcing polyfill in Safari (once CE.v1 are shipped there) just for `is` looks like an overhead.

**Comment by tomalec** [comment]
Luckily https://github.com/Polymer/polymer/pull/4069 get merged so `imported-template` can continue to work well with Polymer 2.0 :)

**Comment by warpech** [comment]
> Luckily Polymer/polymer#4069 get merged so imported-template can continue to work well with Polymer 2.0 :)

That's a great relief, congrats on your code being merged!

**Comment by warpech** [comment]
Closing as won't fix, if you put a `<p>` element as a fallback content then this is the behavior that you get from the web spec.
