### ISSUE TITLE
Upgrade it to (async) CEv1 & update the test

### ISSUE THREAD

**Issue by tomalec** [Juicy/imported-template#30]
We decided to go with `document-register-element` polyfill of CEv1 with `is` attribute as https://github.com/webcomponents/custom-elements/pull/88 is stale. Then, unfortunately, it makes CEReactions asynchronous, so we will have to update the tests for it.

**Comment by warpech** [comment]
After we make `i-t` an autonomous custom element, there is no need for async lifecycle callbacks.

Closing as won't fix.
