### ISSUE TITLE
Why not use a map/hash for scoped nodes?

### ISSUE THREAD

**Issue by alshakero** [Juicy/imported-template#35]
In these lines
https://github.com/Juicy/imported-template/blob/63467b2d58e35a15281ccaa0db2755928658f025/imported-template.html#L88-L89
we set a scope property to the array of templates that fall under that scope.

Then in `starcounter-include` we loop over the array of arrays in a **O(N<sup>2</sup>)** complexity looking for nodes that match our `key`. Why not store all scoped nodes in an object instead of an array?
Instead of:
```js
[
 [node1, node2, node3, scope: 'key1'],
 [node1, node2, node3, scope: 'key2'],
]
```
use:
```js
{ 
 key1: [node1, node2, node3],
 key2: [node1, node2, node3],
}
```

This will make both `imported-template` and `starcounter-include` faster and make the code a tad cleaner.

I can do it if you agree, WDYT @warpech @tomalec

**Comment by tomalec** [comment]
If `N` is the number of nodes it's `O(N)`
```js
[
 [node1, node2, node3, scope: 'key1'],
 [node4, node5, node6, scope: 'key2'],
]
```

I agree the Map would be cleaner, and probably cheaper as instead
```js
this.template.scopedNodes.forEach((nodes) => {
    if(nodes.scope === key) {
        nodes.forEach((node) => appendComposition(merged, node));
    }
});
```
we could do 
```js
this.template.scopedNodes[key].forEach((node) => appendComposition(merged, node));
```

However AFAIR, I did it that way to support cases when we have multiple HTML responses for the same JSON view-model:

```js
[
 [node1, node2, node3, scope: 'key1'],
 [node4, node5, node6, scope: 'key2'],
 [node7, node8, node9, scope: 'key1'],
]
```

Also, the order of elements and scopes matters.

**Comment by alshakero** [comment]
Closing as @tomalec explained why it's unneeded.
