### ISSUE TITLE
Href attribute tries to fetch `undefined` URI from server

### ISSUE THREAD

**Issue by miyconst** [Juicy/imported-template#36]
### Steps to reproduce

```json
{
    "Page": {}
}
```

```html
<template is="imported-template" href="{{model.Page.Uri}}"></template>
```

### Expected result

- Nothing should be shown on the page.
- Nothing should be fetched from the server.

### Actual result

`imported-template` tries to fetch `/undefined` URI from the server.

**Comment by alshakero** [comment]
On it..

**Comment by alshakero** [comment]
Should be fixed in https://github.com/Juicy/juicy-html/pull/34

**Comment by miyconst** [comment]
When I should expect it in the `2.3.1` builds?

**Comment by alshakero** [comment]
In ~20 mins.
